name: Build SunamoThisApp

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoThisApp
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoThisApp/SunamoThisApp.csproj

    - name: Build
      run: dotnet build SunamoThisApp/SunamoThisApp.csproj --configuration Release --no-restore

  test:
    name: Test SunamoThisApp.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoThisApp.Tests/SunamoThisApp.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoThisApp.Tests/SunamoThisApp.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoThisApp.Tests/SunamoThisApp.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
